version: "2"
services:
  db:
    image: postgres:11.0
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5432"
    restart: always
  odoo11:
    image: odoo:11.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "8191:8069"
    tty: true
    command: -- --dev=all
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./mnt/extra-addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      - ./etc/odoo-server.log:/var/log/odoo/odoo-server.log
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=erp@irmaservice.com
      - PGADMIN_DEFAULT_PASSWORD=odoo
    ports:
      - "8081:80"
    restart: always
